### ISSUE TITLE
`mark` oddly interprets input as file where documentation suggests otherwise?

### ISSUE THREAD

**Issue by LukasWallrich** [rstudio/markdown#100]
I frequently use `markdown::mark()`, yet now ran into an issue where `"*F*(5, 7165) = 358.25, *p* < .001"` was interpreted as a filename. Having never looked at the documentation before, it took me a while to figure out where that error came from.

According to the docs `a single character string input will be treated as a file only when the file exists or it has a file extension` - neither seems to be the case here?

``` r
markdown::mark("*F*(5, 7165) = 358.25, *p* < .001")
#> Warning in file(con, "r"): cannot open file '*F*(5, 7165) = 358.25, *p* <
#> .001': No such file or directory
#> Error in file(con, "r"): cannot open the connection
```

<sup>Created on 2023-04-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yihui** [comment]
In this case, `.001` was treated as a "file extension". To ensure the input is text, either use `I()` or the `text` argument:
https://github.com/rstudio/markdown/blob/0f64983eda3c5aeb0fcdd89068241c59f92b4744/man/mark.Rd#L28-L30

```r
markdown::mark(I("*F*(5, 7165) = 358.25, *p* < .001"))
markdown::mark(text = "*F*(5, 7165) = 358.25, *p* < .001")
```

I think the file extension heuristics in `mark()` should be improved and I'll see what I can do. Thanks for the report!

**Comment by yihui** [comment]
Should be fixed now. Thanks again!

**Comment by LukasWallrich** [comment]
Thank you!
