### ISSUE TITLE
xfun::isFALSE

### ISSUE THREAD

**Issue by r2evans** [rstudio/markdown#101]
I get repeated warnings in my code about "`xfun::isFALSE` is deprecated" and that I should shift to `base::isFALSE` to be explicit about it. I know it's just a warning, but there are a couple of uses in this package (e.g., `mark` at least), and since you import `xfun` it seems a propos to shift to `base::isFALSE`.

**Comment by yihui** [comment]
> since you import `xfun` it seems a propos to shift to `base::isFALSE`.

I've done it four months ago: 1768531664a40cb776bd06c157d185b006ac0407

If you [update your R packages](https://yihui.org/en/2017/05/when-in-doubt-upgrade/), the warnings should be gone.

**Comment by r2evans** [comment]
thanks ... we're still seeing it in most shiny apps, so we're trying to iron out exactly where the warning is coming from; I thought this might have been it.

**Comment by yihui** [comment]
Thanks for the report anyway!
