### ISSUE TITLE
How to call markdown::mark_html() without seeing maximum path length warning?

### ISSUE THREAD

**Issue by kenjisato** [rstudio/markdown#103]
On my Mac, a warning message is issued with the following minimal call to `markdown::mark_html()`. 

``` r
. <- markdown::mark_html("hello")
#> Warning in file.info(x, extra_cols = FALSE): expanded path length 1663 would be too long for
#> <style type="text/css">
#> body {
#>   font-family: sans-s [... truncated]
```

<sup>Created on 2023-08-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This warning appears because `xfun::file_exists()`, or ultimately `file.info()`, is attempted against the content of the CSS file. With `default.css`, this warning may only appear on Mac, where the maximum path length is 1023. With a larger CSS file, the same warning could appear on other platforms, I suppose.  

After some struggles, I noticed that this warning shows up only when the `meta$css` is given as an absolute path. 

``` r
oopts <- options()
options(warning.length = 100)

# Copy the default CSS to simulate custom CSS
dir.create(tdir <- tempfile(pattern = "dir", tmpdir = "."))
. <- file.copy(system.file("resources/default.css", package = "markdown"), tdir)
(custom_css <- file.path(tdir, "default.css"))
#> [1] "./dir7b19758ba261/default.css"

# No warning with a relative path
relative <-
  markdown::mark_html("hello", meta = list(css = custom_css))

# Warning appears for an absolute path
absolute <-
  markdown::mark_html("hello", meta = list(css = normalizePath(custom_css)))
#> Warning in file.info(x, extra_cols = FALSE): expanded path length 1663 would be too long for
#> <style type="text/css">
#> body {
#>   font-family: sans-s [... truncated]

unlink(tdir, recursive = TRUE)
options(oopts)
```

<sup>Created on 2023-08-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

My intention is to write a package that calls `markdown::mark()` with a custom CSS, which will be passed with a `system.file()`-generated absolute path. It would be great if there is a clean way to avoid the `file.info()` warning. (i.e., cleaner than using `suppressWarnings()` I mean...)

Would you have any recommendations? Thanks!

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by kenjisato** [comment]
Great. Thanks!

**Comment by yihui** [comment]
You are welcome! You can test it with

```r
install.packages('markdown', repos = c('https://rstudio.r-universe.dev', 'https://cloud.r-project.org'))
```

**Comment by kenjisato** [comment]
Confirmed that it is working!

**Comment by yihui** [comment]
Great. I'll make a new release tomorrow. Thanks!
