### ISSUE TITLE
Unicode may fail the rendering with ` number_sections: true`

### ISSUE THREAD

**Issue by fyuniv** [rstudio/markdown#104]
Thank you for this updated version of markdown. It does as what Yihui said in his slides. I am hoping more people will use it so that finding a solution to an issue will be easier.

It takes me hours to notice that Unicode may cause rendering error if numbering sections is enabled. 
Here is an example.
```markdown
---
title: "Unicodes in Slides May Fail the Rendering"
output:
  markdown::html_format:
    options:
      number_sections: true
---

------------------------

## Title

For the notations involving 𝑦.
```

The error I recieved is
```R
Error in if (h > 1) n[-(1:(h - 1))] else n : 
  missing value where TRUE/FALSE needed
```
A search shows that the code is used in [utils.R line 558](https://github.com/rstudio/markdown/blob/32c3de2a570e21921da1c04770a24b3be5d7375b/R/utils.R#L558).

Although it is not a real issue, it may help those who get the same error message. Hopefully, there will be an update in the future so that unicode won't after numbering, or a warning about this issue in the manual.

**Comment by yihui** [comment]
Could you provide your `xfun::session_info('markdown')`? I can't reproduce the problem on macOS. Thanks!

**Comment by yihui** [comment]
I just committed a possible fix. If you are on Windows and have Rtools, you can install the development version via

```r
remotes::install_github('rstudio/markdown')
```

If not, you can wait for an hour or two and

```r
install.packages('markdown', repos = 'https://rstudio.r-universe.dev')
```

Make sure `packageVersion('markdown') >= '1.8.2')` after installation.

**Comment by fyuniv** [comment]
> I just committed a possible fix. If you are on Windows and have Rtools, you can install the development version via
> 
> ```r
> remotes::install_github('rstudio/markdown')
> ```
> 
> If not, you can wait for an hour or two and
> 
> ```r
> install.packages('markdown', repos = 'https://rstudio.r-universe.dev')
> ```
> 
> Make sure `packageVersion('markdown') >= '1.8.2')` after installation.

Hi Yihui, Thank you for the quick fix. I was running it on Windows. I will update the package to the latest version and test it again. Thank you!
