### ISSUE TITLE
`ggplotly()` not working. 

### ISSUE THREAD

**Issue by fyuniv** [rstudio/markdown#105]
When trying to create an interactive box plot, I noticed that `ggplotly()` does not work as expected. No image was produced/embedded in the output html file. The following is an example.

````markdown

---
title: "Testing `plotly`"
output:
  markdown::html_format
---

```{r setup, echo=FALSE, warning=FALSE}
library(ggplot2)
library(plotly, warn.conflicts = FALSE)
library(htmlwidgets)
```

## Box Plot Without `ggploty()`

```{r echo=FALSE, results = 'asis', fig.width=12, fig.asp=0.4, fig.cap="ggplotly not working", fig.align='center'} 

boxplot<-ggplot(mtcars, aes(x=as.factor(cyl), y=mpg)) + 
    geom_boxplot(fill="royalblue") + 
    xlab("cyl")

boxplot
```

## Box Plot With `ggploty()`

```{r echo=FALSE, results = 'asis', fig.width=12, fig.asp=0.4, fig.cap="Without apply ggploty", fig.align='center'} 
ggplotly(boxplot)
saveWidget(ggplotly(boxplot), file = "plotlyboxplot.html")
```

## ggplotly as an Iframe

```{r echo=FALSE, results = 'asis', fig.width=12, fig.asp=0.4, fig.cap="Without apply ggploty", fig.align='center'} 
saveWidget(ggplotly(boxplot), file = "plotlyboxplot.html")
knitr::include_url("plotlyboxplot.html")
```
````

This is not a big issue and can be resolved. But it will be more convenient to be able to embed directly interactive images produced by the `ggplotly()` function.

**Comment by yihui** [comment]
The lack of support for HTML was documented in the intro vignette: https://cran.r-project.org/web/packages/markdown/vignettes/intro.html (in the section "Comparison to Pandoc")

However, I knew it was possible to support them and just experimented for a while. They should render now. You can install the development version via

```r
remotes::install_github('rstudio/markdown')
```

Or wait for an hour or two and

```r
install.packages('markdown', repos = 'https://rstudio.r-universe.dev')
```

Make sure `packageVersion('markdown') >= '1.8.3')` after installation.
