### ISSUE TITLE
Simple `markdown::knit()` function

### ISSUE THREAD

**Issue by jangorecki** [rstudio/markdown#109]
> Someday you may even be able to get rid of the dependency on **knitr**, since I may provide [a simple `knit()` function](https://github.com/rstats-gsod/gsod2022/issues/5#issuecomment-1048914975) in the **markdown** package.

_Originally posted by @yihui in https://github.com/rstudio/markdown/issues/108#issuecomment-1841924398_
            
Filling the issue so we can subscribe to status of it, see upvotes and discuss why or why not. There are already multiple good "why" comments in the linked discussion.

**Comment by yihui** [comment]
The new knit function is `litedown::fuse()`: https://github.com/yihui/litedown
