### ISSUE TITLE
test_feature() uses Perl regexps, then match_replace() doesn't

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/markdown#112]
I don't have an example to trigger this, but it looks like a bug in this code and similar:

https://github.com/rstudio/markdown/blob/384c45407f91022c26d062884d14e43545be1d6b/R/render.R#L154C1-L163C4

The problem is that `test_feature(...)` calls `grep(pattern, text, perl = TRUE)`, but `match_replace(...)` doesn't specify `perl = TRUE` when it calls `gregexpr(...)`.  

I'm not sure if the fix is to always specify `perl = TRUE` within `match_replace`, or to specify it explicitly in this case and similar ones.

**Comment by yihui** [comment]
Thanks for the report! I changed the default of the `perl` argument here: https://github.com/rstudio/markdown/blob/384c45407f91022c26d062884d14e43545be1d6b/R/utils.R#L2

**Comment by dmurdoch** [comment]
Whoops, didn't see that!
