### ISSUE TITLE
markdown:::.b64EncodeFile -- no longer exists

### ISSUE THREAD

**Issue by williamlai2** [rstudio/markdown#116]
Hi, I've noticed that `markdown:::.b64EncodeFile()` doesn't exist anymore. I tried `base64enc::base64encode()` but it doesn't quite work the same. 

I am using this in a javascript chunk in an RMarkdown notebook, referring to parameters in the YAML.

This is at the bottom of the notebook.

```
<!-- DO NOT DELETE - this script tag adds the logo, title, project and office details (from params) to the table of contents -->
<script>
   $(document).ready(function() {
     $head = $('#TOC');
     $head.prepend('<figure><img src=`r base64enc::base64encode(params$set_logo_path)` style=\"float: center; padding:10px 40px; width: 250px;\"/><figcaption><h2 class="toc">`r params$set_title`</h2></figcaption></figure>' );
     $head.append('<hr><div align="center"><p><small>Job No. `r params$set_job_number`<br>`r params$set_doc_version` <br>`r format(Sys.time(), '%d %B, %Y')`</small></p><p><small>`r params$set_company`<br>`r params$set_office`<br></small></p></div>');
   });
</script>

<hr>
```

**Comment by yihui** [comment]
Yes, this internal function has been removed long ago. `base64enc::base64encode()` probably needs the MIME type info. You may try `xfun::base64_uri()` instead.

**Comment by williamlai2** [comment]
Thanks. I'll try that.

Yes, I was using an old version.

**Comment by williamlai2** [comment]
Thanks `xfun::base64_uri()` works.
