### ISSUE TITLE
Conflicting License info?

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/markdown#117]
Hi,

Is this file meant to still be included with the package?

https://github.com/rstudio/markdown/blob/ae8b8756ca10abbdefbcb37d3d2f817edbee40e4/inst/COPYING

That mentions GPL-2 but the package switched to MIT here: 5d88ec4555a58d20f4d517b434220ea0a4baf704

**Comment by yihui** [comment]
Good catch. I've deleted this file. Thanks!
