### ISSUE TITLE
Is it reasonable to support Chinese punctuation?

### ISSUE THREAD

**Issue by yanlinlin82** [rstudio/markdown#68]
I tried the following code chunk. The emphasis before period (.) could be identified correctly.

    > print(markdown::markdownToHTML(text = "This is a *test*.", fragment.only = TRUE))
    [1] "<p>This is a <em>test</em>.</p>\n"

However, if I use Chinese period (。), it cannot identify the emphasis any more.

    > print(markdown::markdownToHTML(text = "这是个*测试*。", fragment.only = TRUE))
    [1] "<p>这是个*测试*。</p>\n"

**Comment by yihui** [comment]
You need to turn off the extension `no_intra_emphasis`:

```r
print(markdown::markdownToHTML(
  text = "这是个*测试*。",
  extensions = setdiff(markdownExtensions(), 'no_intra_emphasis'),
  fragment.only = TRUE
))
# [1] "<p>这是个<em>测试</em>。</p>\n"
```

This is because Chinese does not have word boundaries like spaces in English.

**Comment by yanlinlin82** [comment]
Thanks!

**Comment by earthcli** [comment]
I wonder how to deal with chinese words within Rmd file when using markdownToHTML?
It works  well directly in the Rstudio, while does not work when using shiny app.
