### ISSUE TITLE
Linking to folder

### ISSUE THREAD

**Issue by davidmartinad200** [rstudio/markdown#69]
HI,
I´m using rstudio together with knitr and markdown. I´m generating a pdf_document.

I have a problem with linking to a local folder on the server where the plots are.
The command:

    The plots are [here](/tmp/plots//)

It seems that when linking to a local folder it adds a ".pdf" extension   file so that it is interpreted as if i was linking to 
/tmp/plots/.pdf   . A ".pdf" extension is added automatically.
The thing is that this folder comtains many files and i don´t want to link to each individually but rather link to the folder.
thanks,

**Comment by yihui** [comment]
It is hard to believe `[]()` will trigger `.pdf`. It is just the syntax for hyperlinks after all. Are you sure you were not talking about `![]()`? I do not understand what a link to a folder actually means in either case.

BTW, this is the markdown repo, and it seems you were talking about **r**markdown: https://github.com/rstudio/rmarkdown

**Comment by davidmartinad200** [comment]
Hi yihui,
I probably didn´t explain very well the problem so i´ll try again.
I´m creating a pdf report file using markdown.
---
title: "Report"
author: "david"
date: "03/Mars/2015"
output: pdf_document
---
I´m trying to access a folder that contains many files. All those files are pdf files on my local disk that are located in my home directory. The command i use to access the folder based on markdown is the following

[folder](/home/david/mydata/myresults/)

As you can see i´m no linking to a file but rather to a folder containing files. This is supposed to open your browser (not your web browser but your folder browser. In my case since i´m under macos it should open the finder to explore that folder). The problem is that markdown thinks this is a folder and try to add automaitcally a .pdf extension to the path. in my case markdown will think that i´m trying to open /home/david/mydata/myresults/.pdf   . If i remove the last slash then markdown thinks i´m trying to open the following file /home/david/mydata/myresults.pdf . No matter what i write it tries to open a pdf file instead of a folder

The problem was also discribed here but since i´m not creting a web report but a pdf report it don´t know how to do it. I guess other people has tried to link to a local folder rather than a file ?? 

http://tex.stackexchange.com/questions/36567/hyperref-how-to-open-a-directory-view-with-href/36613#36613
I would really like to get your help here since i don´t know how to handle this. 
Thanks

**Comment by yihui** [comment]
Okay, it looks hyperref is the culprit according to the SE post you mentioned. I tried the second answer (adding a period after the path), and it worked for me (on Linux). But I guess you have to use relative paths instead of absolute paths. I will leave it you to figure out what the appropriate relative path is in your case. May be this or something else

    [folder](mydata/myresults/.)

**Comment by davidmartinad200** [comment]
OK,
But the problem is that i don´t know how to make my report portable if i use absolut path ?

**Comment by davidmartinad200** [comment]
ok I fix it using 
"\href{run:../folder/}{Relative link to my folder}"
