### ISSUE TITLE
Shortcuts for R code are not working when editing a .Rmd source file

### ISSUE THREAD

**Issue by antoine-lizee** [rstudio/markdown#70]
`ctrl+ alt + F` (sourcing a function) is the shortcut I miss the most.
`ctr + alt + B/E` might be slightly harder to implement (but since "source" `ctrl+shift+R` knows how to source only the chunks already it shouldn't be too hard)

This makes it quite hard to develop R code into the Rmd files directly. I ended up wirting all the code in a normal R file and copy paste at the end :-).

**Comment by antoine-lizee** [comment]
I just realized it might be the wrong place to declare this issue. Any idea where I can report stuff related to the IDE?

**Comment by yihui** [comment]
Please see http://www.rstudio.com/about/support-agreement/

**Comment by antoine-lizee** [comment]
Yup. Sorry. Going to [the official support page](https://support.rstudio.com). (Why not github though? :-D)

**Comment by yihui** [comment]
That's fine. I don't know why not Github, either :) I'm not an IDE developer.
