### ISSUE TITLE
renderMarkdown does not detect LaTeX math in RStudio IDE under Debian (only)

### ISSUE THREAD

**Issue by jonathan-g** [rstudio/markdown#71]
A weird anomaly:

I run this script in several environments:

```
rm(list = ls())

library(markdown)

eq <- 'x = \\sqrt{\\left[\\frac{y^z}{\\theta}\\right]}'

p_text <- paste0('$',   eq, '$')
q_text <- paste0('$$',  eq, '$$')
r_text <- paste0('\\(', eq, '\\)')
s_text <- paste0('\\[', eq, '\\]')

p <- renderMarkdown(text = p_text)
q <- renderMarkdown(text = q_text)
r <- renderMarkdown(text = r_text)
s <- renderMarkdown(text = s_text)

cat(p_text, '-->', p, '\n')
cat(q_text, '-->', q, '\n')
cat(r_text, '-->', r, '\n')
cat(s_text, '-->', s, '\n')

cat('markdown.extensions:', unlist(getOption('markdown.extensions')), '\n')
cat('markdown.HTML.options:', unlist(getOption('markdown.HTML.options')), '\n')

print(sessionInfo())
```

Under Debian using `RScript` or sourcing it interactively from `R`, I get this output:

```
$x = \sqrt{\left[\frac{y^z}{\theta}\right]}$ --> <p>\(x = \sqrt{\left[\frac{y^z}{\theta}\right]}\)</p>

$$x = \sqrt{\left[\frac{y^z}{\theta}\right]}$$ --> <p>\[x = \sqrt{\left[\frac{y^z}{\theta}\right]}\]</p>

\(x = \sqrt{\left[\frac{y^z}{\theta}\right]}\) --> <p>\(x = \sqrt{\left[\frac{y^z}{\theta}\right]}\)</p>

\[x = \sqrt{\left[\frac{y^z}{\theta}\right]}\] --> <p>\[x = \sqrt{\left[\frac{y^z}{\theta}\right]}\]</p>

markdown.extensions: no_intra_emphasis tables fenced_code autolink strikethrough lax_spacing space_headers superscript latex_math 
markdown.HTML.options: use_xhtml smartypants base64_images mathjax highlight_code 
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] markdown_0.7.7
```

When I run it under RStudio IDE or RStudio Server (both version 0.99.441 installed from the .deb files downloaded from RStudio.com) I get this:

```
$x = \sqrt{\left[\frac{y^z}{\theta}\right]}$ --> <p>$x = \sqrt{\left[\frac{y<sup>z}{\theta}\right]}$</sup></p>

$$x = \sqrt{\left[\frac{y^z}{\theta}\right]}$$ --> <p>$$x = \sqrt{\left[\frac{y<sup>z}{\theta}\right]}$$</sup></p>

\(x = \sqrt{\left[\frac{y^z}{\theta}\right]}\) --> <p>(x = \sqrt{\left[\frac{y<sup>z}{\theta}\right]})</sup></p>

\[x = \sqrt{\left[\frac{y^z}{\theta}\right]}\] --> <p>[x = \sqrt{\left[\frac{y<sup>z}{\theta}\right]}]</sup></p>

markdown.extensions: no_intra_emphasis tables fenced_code autolink strikethrough lax_spacing space_headers superscript latex_math 
markdown.HTML.options: use_xhtml smartypants base64_images mathjax highlight_code 
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] markdown_0.7.7

loaded via a namespace (and not attached):
[1] tools_3.2.0
```

And when I run it under RStudio IDE on Windows 7, I get this:

```
$x = \sqrt{\left[\frac{y^z}{\theta}\right]}$ --> <p>\(x = \sqrt{\left[\frac{y^z}{\theta}\right]}\)</p>

$$x = \sqrt{\left[\frac{y^z}{\theta}\right]}$$ --> <p>\[x = \sqrt{\left[\frac{y^z}{\theta}\right]}\]</p>

\(x = \sqrt{\left[\frac{y^z}{\theta}\right]}\) --> <p>\(x = \sqrt{\left[\frac{y^z}{\theta}\right]}\)</p>

\[x = \sqrt{\left[\frac{y^z}{\theta}\right]}\] --> <p>\[x = \sqrt{\left[\frac{y^z}{\theta}\right]}\]</p>

markdown.extensions: no_intra_emphasis tables fenced_code autolink strikethrough lax_spacing space_headers superscript latex_math 
markdown.HTML.options: use_xhtml smartypants base64_images mathjax highlight_code 
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] markdown_0.7.7

loaded via a namespace (and not attached):
[1] tools_3.2.0
```

Somehow the markdown packages is failing to detect LaTeX equations, but only when I run it under RStudio under Debian. I get the correct behavior in RStudio under Windows and when I run R from the command line. I have reproduced this on two different Windows computers and two different Debian computers.

**Comment by jonathan-g** [comment]
I have done a little experimenting and something very weird seems to be happening.  

If I grab the source for the R package from github and build a local version, with some `Rprintf` statements sprinkled in so I can see what's getting called, it looks to me as though in the RStudio environment in Debian, when `render_to_html` (in Rmarkdown.C) calls `sd_markdown_render` (in markdown.c), the `sd_markdown_render` function from the markdown package is not executed. Something is executed because the markdown is transformed into (incorrect) HTML, but it looks as though it's not the `sd_markdown_render` function in the markdown package.

If I stick `Rprintf` statements just before and after the call to `sd_markdown_render(htmlbuf, ib->data, ib->size, markdown)` in Rmarkdown.c and also at the beginning and end of the `sd_markdown_render` function in markdown.c, in Rstudio under Debian, the `Rprintf` statements in `render_to_html` produce output in the console window, but the `Rprintf` statements in `sd_markdown_render` do not. 

When I run the same R code from the command line on Debian with Rscript, all of the `Rprintf` statements produce output (both in `render_to_html` and `sd_markdown_render`). If I build my modified markdown package on Windows, all the `Rprintf` statements produce output in the console window. But in Rstudio on Debian, the `Rprintf` statements in `sd_markdown_render` do not produce output.

Finally, if I rename the function `sd_markdown_render` (globally search and replace `sd_markdown_render` with `foo_markdown_render`) throughout the markdown packages, and then rebuild the package, it runs fine when I call `renderMarkdown` from the command line R, but when I call `renderMarkdown` in RStudio it crashes rsession, leaving an error message in syslog saying 
```
Jun 16 18:11:56 ornette rsession-<username>[18508]: ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1741
```

Looking a bit deeper, I see that in the source for RStudio, there's a version of markdown.c that's different from the one in the markdown pacakge. I wonder whether somehow, when I am running RStudio on Debian there's a conflict between the version of markdown.c built into rsession and the one in the markdown package. That seems strange, but it's the best explanation I can come up with for what I'm seeing.

**Comment by jonathan-g** [comment]
Just checked on an Ubuntu system (14.0.2 LTS) and markdown behaves just fine under RStudio there. Weird.

**Comment by jjallaire** [comment]
Incredible sleuthing! I would agree with your assessment that there is some symbol crosstalk between the RStudio binary and the functions in the markdown package. I've just made a change to RStudio to rename all of these functions with an `rs_` prefix which I'm hopeful will resolve the problem: 

https://github.com/rstudio/rstudio/commit/44f91312e9980840d8d1b86726724316b290a3f7

This will be available in a daily build sometime later on today (will let you know when it's ready).

**Comment by jjallaire** [comment]
The latest daily build has this fix:

http://www.rstudio.org/download/daily/desktop/

Note however that there isn't currently a Windows version of this daily
(the build failed for some reason). You should however be able to test out
the fix on Debian.

**Comment by jonathan-g** [comment]
Thanks for the quick response, but I have some bad news to report. The new version of RStudio (0.99.595) now crashes on Debian jessie when I call renderMarkdown.

I uninstalled the old version: `sudo apt-get remove rstudio`, then installed the new version for ubuntu 64 from https://s3.amazonaws.com/rstudio-dailybuilds/rstudio-0.99.595-amd64.deb and now rsession crashes (Rstudio displays the bomb with "R Session Aborted") when I run
```
library(markdown)
renderMarkdown(text='foo')
```
The same build works just fine under Ubuntu 14.04.2..

I'm not sure how to generate useful information for you from this, but I'd be happy to help if you can tell me what would be useful to you.

**Comment by jjallaire** [comment]
Okay, I'll have to revert that change then.

BTW not sure if you seen but we've massively upgraded R Markdown based on
the newer rmarkdown package: http://rmarkdown.rstudio.com/ which you might
also consider using (as the older "markdown" package is effectively
deprecated)

**Comment by jonathan-g** [comment]
Yes, I absolutely love the new rmarkdown and knitr for a lot of things and I use it frequently.

But when I am using markdown to generate html slide decks (mostly for revealjs), Ramnath V's slidify approach using mustache templates makes it a lot easier for me to tweak md to html translation.

I spent a lot of time last fall figuring out how to tweak rmarkdown to do what I wanted with revealjs output, but pandoc is very limiting (especially with fine-tuning stuff like incremental bullets and vertical slides) and it is much easier to get what I want with slidify, which uses renderMarkdown as its guts.

I'll keep poking around at this and see if I can come up with a workaround for Debian.

**Comment by ramnathv** [comment]
@jonathan-g I will be switching `slidify` over to `rmarkdown` or `commonmark`. That should hopefully take care of the math issues you have outlined here.
