### ISSUE TITLE
shiny presentation not working

### ISSUE THREAD

**Issue by ignacio82** [rstudio/markdown#72]
[This](https://ignacio.shinyapps.io/error/error.Rmd) very simple example is not working: The presentation has one slide with rChart and one with a shiny histogram. If you go to the shiny slide the histogram will not be displayed. If you reload the webpage the histogram will load. This is the code:

``````

---
title: "Untitled"
author: "Ignacio"
date: "6/18/2015"
output: 
  slidy_presentation
runtime: shiny

---

## Slide with rCharts 

```{r, comment = NA, results = "asis", tidy = F, echo=F}
library(rCharts)
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
n1$set(width = 1024)
n1$show('iframesrc', cdn = TRUE)
```

## Slide with Interactive Plot

```{r, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),

  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")

  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```
``````

Thanks for the help!

**Comment by lmccusker** [comment]
I am also having the same issue, and it is also caused by this DataTables slide:

```{r, echo=FALSE}
library(DT)
iris2 = iris[c(1:10, 51:60, 101:110), ]
datatable(iris2, filter = 'top', options = list(
  pageLength = 5, autoWidth = TRUE
))
```

Sometimes it works the first time, but most of the time it does not work and needs to be reloaded from the slide.

**Comment by ramnathv** [comment]
This is an issue with `rCharts` since it is not implemented as a `htmlwidget` yet. What is happening here is that some dependencies are getting loaded twice, which is leading to the problem. One option for now is to render the `rchart` in an `iframe` so that it is sandboxed. A `htmlwidgets` compatible version of the `rCharts` libraries will be out soon and then you can use things without trouble.

**Comment by ignacio82** [comment]
Thanks @ramnathv ! 
How do I render the `rchart` in an iframe? Is the same for `DT`?

**Comment by marielfinucane** [comment]
I'm having the same issue too. Thanks in advance for any advice!

**Comment by yihui** [comment]
@lmccusker Can you provide a minimal self-contained reproducible example? I cannot reproduce the DT problem you mentioned.

**Comment by ignacio82** [comment]
@yihui the problem seems to be associated to `slidy_presentation`, when I switch to `ioslides_presentation` the problem goes away. My reason to use `slidy_presentation` is that creating a personalized theme is easier.

**Comment by yihui** [comment]
@ignacio82 I don't know your rCharts problem. I was asking @lmccusker about DT. If there is any issue with DT, I can investigate it. Thanks!
