### ISSUE TITLE
Out of memory with .b64EncodeFile() - maximum output size is 16 MiB

### ISSUE THREAD

**Issue by HenrikBengtsson** [rstudio/markdown#76]
The maximum size of the Base64-encoded string generated by `.b64EncodeFile()` is 16 MB.  More specifically, it is hardwired by constant `BUFFER_MAX_ALLOC_SIZE` in [src/buffer.c](https://github.com/rstudio/markdown/blob/master/src/buffer.c#L18):

``` c
#define BUFFER_MAX_ALLOC_SIZE (1024 * 1024 * 16)
```

which equals 16,777,216 bytes.

R example illustrating this:

``` r
library(markdown)

## Maximum buffer size (from markdown/src/buffer.c)
BUFFER_MAX_ALLOC_SIZE <- (1024 * 1024 * 16)

## Create base64 string of zero-vector of a given length
b64empty <- function(n) {
  raw <- raw(length=n)
  .Call(markdown:::rmd_b64encode_data, raw)
}

b64test <- function(n) {
  message(sprintf("Input length: %d", n))
  data <- b64empty(n)
  str(data)
  n_out <- nchar(data)
  message(sprintf("Output length: %d (%.1f%%)", n_out, 100*n_out/n))
  invisible(data)
}
```

and then

``` r
> BUFFER_MAX_ALLOC_SIZE
[1] 16777216

> b64test(12582909)
Input length: 12582909
 chr "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"| __truncated__
Output length: 16777212 (133.3%)

> b64test(12582910)
Input length: 12582910
 NULL

Warning message:
In b64empty(n) : Out of memory!
```

(In order for this example to work, you need the most recent version available on the master branch)

Since 16 MiB is not very big these days, there is really no reason for allowing larger outputs.  In the end, these Base64-encoded strings are typically parsed by HTML web browsers, which themselves might have a maximum length limitation, but those lengths vary greatly and should be increased over time.  In other words, I don't think it is up to the markdown package to specify an upper limit.

Also, the [warning message](Out of memory!) is rather non-informative, but we're not really running out of memory.  Maybe something like, "Failed, because internal 'markdown' buffer reached it's maximum size of 16,777,216 bytes".

I suggest to increase `BUFFER_MAX_ALLOC_SIZE` and to give a more informative message when the maximum limit is reached.

**Comment by yihui** [comment]
I've retired the C code in this package and the base64 encoding is now done via `xfun::base64_encode()`, which has no limit on the size.
