### ISSUE TITLE
rpubsUpload() Error in RCurl::curlOptions(url, cainfo = sslpath)

### ISSUE THREAD

**Issue by englianhu** [rstudio/markdown#78]
Related https://github.com/yihui/knitr/issues/1113#issue-110701689
```diff
> library('markdown')
> rpubsUpload('Coursera Data Science Capstone - Quiz01', 'Quiz01.html')
- Error in RCurl::curlOptions(url, cainfo = sslpath) : 
-   unnamed curl option(s): https://api.rpubs.com/api/v1/document
```

**Comment by englianhu** [comment]
http://rpubs.com/englianhu/Coursera-Data-Science-Capstone-Quiz01
open *Quiz01.html* in editor mode and preview, published. Resolved

**Comment by AzulCeleste** [comment]
How can I open Quiz01.html in an editor mode? I couldn't find even the file.
