### ISSUE TITLE
Test b64EncodeFile without the network?

### ISSUE THREAD

**Issue by QuLogic** [rstudio/markdown#83]
`tests/b64EncodeFile.R` downloads an image from https://www.r-project.org/Rlogo.png. When [building distro packages](https://copr.fedorainfracloud.org/coprs/qulogic/IRkernel/build/593983/), we do not have access to the network and this fails.

AFAIU, downloading is ancillary to the test. Can this test be written in a way that doesn't use the network?

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by QuLogic** [comment]
Thanks, it [works](https://copr.fedorainfracloud.org/coprs/qulogic/IRkernel/build/594275/)!
