### ISSUE TITLE
Still error

### ISSUE THREAD

**Issue by seungheekang** [rstudio/markdown#84]
WARNING: You are configured to use the CRAN mirror at https://cran.rstudio.com/. This mirror supports secure (HTTPS) downloads however your system is unable to communicate securely with the server (possibly due to out of date certificate files on your system). Falling back to using insecure URL for this mirror.

To learn more and/or disable this warning message see the "Use secure download method for HTTP" option in Tools -> Global Options -> Packages.
> radiant:::radiant()
Starting Radiant ...
Loading required package: shiny

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout

Warning in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/???/Documents": 파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다
Warning in dir.create(.) :
  cannot create dir 'C:\Users\???\Documents\radiant.sessions', reason 'Invalid argument'
Warning in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/???/Documents": 파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다
Warning in dir.create(.) :
  cannot create dir 'C:\Users\???\Documents\radiant.sessions', reason 'Invalid argument'

Listening on http://127.0.0.1:7072
Warning in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/???/Documents/radiant.sessions/": 파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다
Warning in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/???/Documents/radiant.sessions/": 파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다
Warning in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/???/Documents/radiant.sessions": 파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다
Warning in gzfile(file, mode) :
  cannot open compressed file 'C:\Users\???\Documents\radiant.sessions/r_local-bf4640.rds', probable reason 'Invalid argument'
Warning: Error in gzfile: cannot open the connection
Stack trace (innermost first):
    39: gzfile
    38: saveRDS
    37: saveSession [c:/R/R-3.4.1/library/radiant.data/app/radiant.R#26]
    30: isolate
    29: callback [c:/R/R-3.4.1/library/radiant.data/app/radiant.R#43]
     2: shiny::runApp
     1: radiant:::radiant

**Comment by seungheekang** [comment]
i got error as above. 
Please check

**Comment by wch** [comment]
It's unclear what this issue has to do with the markdown package.
