### ISSUE TITLE
renderPlot in a rmarkdown: does not recognize mydata (loaded data.table)

### ISSUE THREAD

**Issue by MelissaLe44** [rstudio/markdown#86]
I try to include interactive plots in my rmarkdown.
My dataset (mydata) comes from a .rdata that I load into a r chunk global
In another r chunk, I got my selectinput and my renderPlot that is based on plotting a subset of mydata depending on selectinput.
It does not work because it does not recognize mydata. However if instead I use renderPrint to compute the length of subset of mydata, this works! so it seems it is only a problem with renderPlot!! Using ggplot, I specify environnment=environnment() but this is not working!!
Any advice?

Thanks,
Best
Mélissa

**Comment by yihui** [comment]
You seem to have filed the issue to a wrong repo: https://github.com/rstudio/markdown

You probably meant shiny: https://github.com/rstudio/shiny

**Comment by MelissaLe44** [comment]
I still think it should be in rmarkdown, because a shiny app works with loading a dataset, this is really an issue that I have only while embedding shiny within rmarkdown. I will also put it in Shiny.

**Comment by yihui** [comment]
This is the markdown repo instead of rmarkdown.

Anyway, please always provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/) when reporting an issue.
