### ISSUE TITLE
Compile on IBM Power

### ISSUE THREAD

**Issue by dkinghvt** [rstudio/markdown#88]
Using R 3.3.3 (and later), on IBM Power LPAR, Red Hat 7 PPC65le, markdown build fails as below.  Any assistance is appreciated.

> install.packages("markdown")
trying URL 'https://cloud.r-project.org/src/contrib/markdown_0.8.tar.gz'
Content type 'unknown' length 80583 bytes (78 KB)
==================================================
downloaded 78 KB

* installing *source* package ‘markdown’ ...
** package ‘markdown’ successfully unpacked and MD5 sums checked
** libs
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c Rbase64.c -o Rbase64.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c Rinit.c -o Rinit.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c Rmarkdown.c -o Rmarkdown.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c autolink.c -o autolink.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c buffer.c -o buffer.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c houdini_href_e.c -o houdini_href_e.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c houdini_html_e.c -o houdini_html_e.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c html.c -o html.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c html_smartypants.c -o html_smartypants.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c markdown.c -o markdown.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -I/usr/local/lib64/R/include -DNDEBUG  -I/usr/local/include    -qpic  -g -O2 -qstrict -qfloat=nomaf:fenv  -c stack.c -o stack.o
/opt/ibm/xlC/13.1.6/bin/xlc_r -q64 -qmkshrobj -shared -L/usr/local/lib64/R/lib -L/usr/local/lib64 -o markdown.so Rbase64.o Rinit.o Rmarkdown.o autolink.o buffer.o houdini_href_e.o houdini_html_e.o html.o html_smartypants.o markdown.o stack.o -L/usr/local/lib64/R/lib -lR
markdown.o: In function `find_block_tag':
/tmp/RtmpqYsbzz/R.INSTALL1cb764af1cf/markdown/src/./html_blocks.h:206: undefined reference to `find_block_tag$AF85_1'
/usr/bin/ld: markdown.so: internal symbol `find_block_tag$AF85_1' isn't defined
/usr/bin/ld: final link failed: Bad value
make: *** [markdown.so] Error 1
ERROR: compilation failed for package ‘markdown’
* removing ‘/usr/local/lib64/R/library/markdown’

The downloaded source packages are in
        ‘/tmp/Rtmpl7vFYx/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("markdown") :
  installation of package ‘markdown’ had non-zero exit status
>

**Comment by hubert-reinterpretcast** [comment]
Can you try adding `-fgnu89-inline` to the compiler options? There seems to be some compiler issue with the handling of the `__gnu_inline__` function attribute.

**Comment by dkinghvt** [comment]
-fgnu89-inline seems to have helped, significantly.

**Comment by dkinghvt** [comment]
For posterity, the compilers are:
IBM_XL_FORTRAN_V15.1.6.1_LINUX_COMMUNITY.tar.gz
IBM_XL_C_CPP_V13.1.6.1_LINUX_COMMUNITY.tar.gz

**Comment by dkinghvt** [comment]
Also, thank you!
