### ISSUE TITLE
Is it possible to allow package units to play well with rmarkdown pdf document generation?

### ISSUE THREAD

**Issue by pm321** [rstudio/markdown#90]
rmarkdown does not seem to recognise or print units from the units package. 

Please refer to stackoverflow question for reproducible code: [How to use units package with rmarkdown for pdf document](https://stackoverflow.com/questions/50299748/how-to-use-units-package-with-rmarkdown-for-pdf-document)

**Comment by yihui** [comment]
This is the **markdown** repo. The **rmarkdown** repo is at https://github.com/rstudio/rmarkdown.

**Comment by yihui** [comment]
Duplicate of https://github.com/rstudio/rmarkdown/issues/1341
