### ISSUE TITLE
Encoding issue in test

### ISSUE THREAD

**Issue by tillea** [rstudio/markdown#97]
Hi,
when trying to update the Debian packaged markdown to version 1.3 I was running into some encoding issue:

    --- tests.Rout.save_        2022-11-15 11:07:46.657421772 +0000
    +++ tests.Rout_     2022-11-15 11:07:46.661421765 +0000
    @@ -70,7 +70,7 @@
     \end{eqnarray}</p>

     > cat(mark("1/2 (c)"))
    -<p>½ ©</p>
    +<p><U+00BD> <U+00A9></p>

     > cat(mark("1/2 (c)", options = "-smartypants"))
     <p>1/2 (c)</p>
    @@ -80,7 +80,7 @@
     > mkd <- paste(c(mkd, paste0("`", mkd, "`")), collapse = " ")

     > cat(mark(mkd))
    -<p>½ ⅓ ⅔ ¼ ¾ ⅕ ⅖ ⅗ ⅘ ⅙ ⅚ ⅛ ⅜ ⅝ ⅞ ⅐ ⅑ ⅒ © ® ™ <code>1/2</code> <code>1/3</code> <code>2/3</code> <code>1/4</code> <code>3/4</code> <code>1/5</code> <code>2/5</code> <code>3/5</code> <code>4/5</code> <code>1/6</code> <code>5/6</code> <code>1/8</code> <code>3/8</code> <code>5/8</code> <code>7/8</code> <code>1/7</code> <code>1/9</code> <code>1/10</code> <code>(c)</    code> <code>(r)</code> <code>(tm)</code></p>
    +<p><U+00BD> <U+2153> <U+2154> <U+00BC> <U+00BE> <U+2155> <U+2156> <U+2157> <U+2158> <U+2159> <U+215A> <U+215B> <U+215C> <U+215D> <U+215E> <U+2150> <U+2151> <U+2152> <U+00A9> <U+    00AE> <U+2122> <code>1/2</code> <code>1/3</code> <code>2/3</code> <code>1/4</code> <code>3/4</code> <code>1/5</code> <code>2/5</code> <code>3/5</code> <code>4/5</code> <code>1/6</code>  <code>5/6</code> <code>1/8</code> <code>3/8</code> <code>5/8</code> <code>7/8</code> <code>1/7</code> <code>1/9</code> <code>1/10</code> <code>(c)</code> <code>(r)</code> <code>(tm)</   code></p>

     > cat(mark(mkd, options = "-smartypants"))
     <p>1/2 1/3 2/3 1/4 3/4 1/5 2/5 3/5 4/5 1/6 5/6 1/8 3/8 5/8 7/8 1/7 1/9 1/10 (c) (r) (tm) <code>1/2</code> <code>1/3</code> <code>2/3</code> <code>1/4</code> <code>3/4</code>        <code>1/5</code> <code>2/5</code> <code>3/5</code> <code>4/5</code> <code>1/6</code> <code>5/6</code> <code>1/8</code> <code>3/8</code> <code>5/8</code> <code>7/8</code> <code>1/7</     code> <code>1/9</code> <code>1/10</code> <code>(c)</code> <code>(r)</code> <code>(tm)</code></p>
    @@ -110,7 +110,7 @@
     > cat(mark("\nFirst Header  | Second Header\n------------- | -------------\nContent Cell  | Content Cell\nContent Cell  | Content Cell\n",
     +     opti .... [TRUNCATED]
     <p>First Header  | Second Header
    -———–– | ———––
    +<U+2014><U+2014><U+2014><U+2013><U+2013> | <U+2014><U+2014><U+2014><U+2013><U+2013>
     Content Cell  | Content Cell
     Content Cell  | Content Cell</p>

You can find a full log of the test suite in the [Debian CI](https://salsa.debian.org/r-pkg-team/r-cran-markdown/-/jobs/3519402).

Kind regards, Andreas.

**Comment by yihui** [comment]
This has been fixed a week ago (81a203cfc432334654fa6011c5eddbe483b2ec8e). The new version 1.4 is on CRAN now: https://cran.r-project.org/package=markdown Thanks!
